string1=input("Enter Content Of File 1:")
f1=open('abc.txt','w+')
f1.write(string1)
f1.seek(0,0)
print("\nReading From abc File")
string2=f1.read()
print(string2)
f1.close()

f2=open('xyz.txt','w+')
f2.write(string2)
f2.seek(0,0)
print("\nReading From xyz File ")
print(f2.read())
f2.close()
